// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyrrdmkqsdlwjcjrypyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55cnJkbWtxc2Rsd2pjanJ5cHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NDg2MTEsImV4cCI6MjA5MDMyNDYxMX0.V3SafRjITKa3BVI1ERbO0XKJeGqBHn3FLklp7w1ZMgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});